import type { Product, Order } from "@/contexts/AppContext"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Ultra High-Rise Denim Jeans",
    price: 3383,
    salePrice: 2368,
    image: "/placeholder.svg?height=400&width=300",
    images: [
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
    ],
    category: "Women",
    subcategory: "Jeans",
    brand: "KoLaz",
    colors: ["Blue", "Black", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 25,
    isNewArrival: true,
    isBestSeller: true,
    isFeatured: true,
    description:
      "Premium ultra high-rise denim jeans crafted from sustainable cotton blend. Features a flattering silhouette with stretch comfort.",
    tags: ["denim", "high-rise", "sustainable", "premium"],
  },
  {
    id: "2",
    name: "Oversized Cotton Hoodie",
    price: 1899,
    image: "/placeholder.svg?height=400&width=300",
    images: ["/placeholder.svg?height=400&width=300"],
    category: "Unisex",
    subcategory: "Hoodies",
    brand: "KoLaz",
    colors: ["Gray", "Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 40,
    isNewArrival: false,
    isBestSeller: true,
    isFeatured: false,
    description: "Comfortable oversized hoodie made from 100% organic cotton.",
    tags: ["cotton", "oversized", "comfort"],
  },
  {
    id: "3",
    name: "Silk Blend Midi Dress",
    price: 4299,
    salePrice: 3439,
    image: "/placeholder.svg?height=400&width=300",
    images: ["/placeholder.svg?height=400&width=300"],
    category: "Women",
    subcategory: "Dresses",
    brand: "KoLaz",
    colors: ["Black", "Navy", "Burgundy"],
    sizes: ["XS", "S", "M", "L"],
    stock: 15,
    isNewArrival: true,
    isBestSeller: false,
    isFeatured: true,
    description: "Elegant silk blend midi dress perfect for special occasions.",
    tags: ["silk", "midi", "elegant", "formal"],
  },
  {
    id: "4",
    name: "Classic White Sneakers",
    price: 2799,
    image: "/placeholder.svg?height=400&width=300",
    images: ["/placeholder.svg?height=400&width=300"],
    category: "Unisex",
    subcategory: "Shoes",
    brand: "KoLaz",
    colors: ["White", "Black"],
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    stock: 30,
    isNewArrival: false,
    isBestSeller: true,
    isFeatured: false,
    description: "Timeless white sneakers with premium leather construction.",
    tags: ["sneakers", "leather", "classic", "comfortable"],
  },
]

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    userId: "user-1",
    items: [
      {
        id: "cart-1",
        product: mockProducts[0],
        size: "M",
        color: "Blue",
        quantity: 1,
      },
    ],
    total: 2368,
    status: "processing",
    paymentMethod: "cod",
    shippingAddress: {
      id: "addr-1",
      fullName: "John Doe",
      phone: "+8801234567890",
      address: "123 Fashion Street",
      city: "Dhaka",
      zip: "1000",
      isDefault: true,
    },
    createdAt: "2024-01-15T10:30:00Z",
    trackingId: "TRK123456789",
  },
]

export const categories = [
  { id: "1", name: "Women", image: "/placeholder.svg?height=300&width=300" },
  { id: "2", name: "Men", image: "/placeholder.svg?height=300&width=300" },
  { id: "3", name: "Unisex", image: "/placeholder.svg?height=300&width=300" },
  { id: "4", name: "Accessories", image: "/placeholder.svg?height=300&width=300" },
]

export const benefits = [
  {
    title: "Free Shipping",
    description: "Free shipping on orders over ৳2000",
    icon: "🚚",
  },
  {
    title: "Easy Returns",
    description: "30-day hassle-free returns",
    icon: "↩️",
  },
  {
    title: "Premium Quality",
    description: "Carefully curated premium fashion",
    icon: "✨",
  },
]
